import { NextRequest, NextResponse } from "next/server"
import { createAdminClient } from "@/lib/supabase/admin"

// GET /api/leader/team-leads?email=X
// Returns all leads generated by the leader AND their direct downline (referrals).
// Used by the /leader/leads page so sponsors can see their team's lead activity.

export async function GET(req: NextRequest) {
  try {
    const email = req.nextUrl.searchParams.get("email")
    if (!email) {
      return NextResponse.json({ error: "Email requerido" }, { status: 400 })
    }

    const supabase = createAdminClient()
    if (!supabase) return NextResponse.json({ leads: [], stats: {} })

    const normalized = email.toLowerCase().trim()

    // 1. Find the leader's own community_members record
    const { data: leader } = await supabase
      .from("community_members")
      .select("member_id, name, username, community_id")
      .eq("email", normalized)
      .maybeSingle()

    if (!leader) return NextResponse.json({ leads: [], stats: {} })

    // 2. Get direct referrals (members who listed this leader as sponsor)
    const { data: referrals } = await supabase
      .from("community_members")
      .select("member_id, name, username, email, activo")
      .eq("sponsor_username", leader.username)

    const referralList = referrals || []

    // 3. Build all identifiers we should query leads for (leader + all downline)
    const identifiers = new Set<string>()

    if (leader.username) identifiers.add(leader.username)
    if (leader.member_id) identifiers.add(leader.member_id)

    for (const ref of referralList) {
      if (ref.username) identifiers.add(ref.username)
      if (ref.member_id) identifiers.add(ref.member_id)
    }

    identifiers.delete("")
    const idArray = Array.from(identifiers)

    if (idArray.length === 0) return NextResponse.json({ leads: [], stats: {} })

    // 4. Fetch all leads assigned to any of those identifiers
    const { data: leads, error } = await supabase
      .from("leads")
      .select("id, nombre, email, whatsapp, etapa, fuente, fecha_ingreso, asignado_a, community_id")
      .in("asignado_a", idArray)
      .order("fecha_ingreso", { ascending: false })

    if (error) {
      console.error("[leader/team-leads] leads fetch error:", error.message)
      return NextResponse.json({ error: "Error al cargar leads" }, { status: 500 })
    }

    const allLeads = leads || []

    // 5. Build a lookup map: identifier -> member display name
    const memberMap = new Map<string, string>()
    if (leader.username) memberMap.set(leader.username, leader.name)
    if (leader.member_id) memberMap.set(leader.member_id, leader.name)
    for (const ref of referralList) {
      if (ref.username) memberMap.set(ref.username, ref.name)
      if (ref.member_id) memberMap.set(ref.member_id, ref.name)
    }

    // Build set of downline identifiers for stats
    const downlineIds = new Set<string>()
    for (const ref of referralList) {
      if (ref.username) downlineIds.add(ref.username)
      if (ref.member_id) downlineIds.add(ref.member_id)
    }

    // 6. Enrich leads with the name of who generated them
    const enriched = allLeads.map((l) => ({
      ...l,
      asignado_nombre: memberMap.get(l.asignado_a) || l.asignado_a,
      es_downline: downlineIds.has(l.asignado_a),
    }))

    // 7. Aggregate stats
    const total = enriched.length
    const conversiones = enriched.filter((l) => l.etapa === "cerrado").length
    const downlineLeads = enriched.filter((l) => l.es_downline).length
    const directLeads = total - downlineLeads

    return NextResponse.json({
      leads: enriched,
      referrals: referralList,
      stats: {
        total,
        conversiones,
        downlineLeads,
        directLeads,
        referralCount: referralList.length,
      },
    })
  } catch (err) {
    console.error("[leader/team-leads] error:", err)
    return NextResponse.json({ error: "Error interno" }, { status: 500 })
  }
}
